# This is a basic usage of python lint referenced in https://medium.com/juntos-somos-mais/python-lint-com-github-actions-d4c01423136

name: Python Lint

# This action is triggered by push
on: [push]

jobs:
  # Now this workflow contains a single job called lint
  lint:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install requirements
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: pyLint runner
        run: |
            python lint.py -p ./winx_sistema/winx_sistema -t 7
            python lint.py -p ./winx_sistema/winx_sistema_loja -t 0.5

